server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://github.com/JoanVasquez/spring-microservice-vehicles
          search-paths: config-data
  application:
    name: config-service